// angular_src/src/app/components/register/register.component.ts
import { Component } from '@angular/core';
import { RouterLink } from '@angular/router';
import { FormsModule } from '@angular/forms';
import { ValidateService } from '../../services/validate.service';
import { AuthService } from '../../services/auth.service';
import { Router } from '@angular/router';

@Component({
  selector: 'app-register',
  standalone: true,
  imports: [ FormsModule, RouterLink ],
  templateUrl: './register.component.html',
  styleUrl: './register.component.css'
})
export class RegisterComponent {
  name: string = '';
  email: string = '';
  password: string = '';

  constructor(
    private validateService: ValidateService,
    private authService: AuthService,
    private router: Router
  ) { }

  onRegisterSubmit() {
    const user = {
      name: this.name,
      email: this.email,
      password: this.password
    };

    // Validate the form data
    if (!this.validateService.validateRegister(user)) {
      // Registration successful message
      alert('Please fill in all fields correctly.');
    } else if (!this.validateService.validateEmail(user.email)) {
      // Show an error message if email is invalid
      alert('Please enter a valid email address.');
    }
    // Register the user
    this.authService.registerUser(user).subscribe(data => {
      if (data.success) {
        // Registration successful message
        alert('You are now registered and can log in.');
        // Redirect to login page
        this.router.navigate(['/login']);
      } else {
        // Show an error message if registration fails
        alert('Something went wrong. Please try again.');
        this.router.navigate(['/register']);
      }
    });
  }
}



<div class="container">
    <h2 class="page-header">Register</h2>
    <form (ngSubmit)="onRegisterSubmit()">
        <div class="form-group">
            <label for="name">Name</label>
            <input type="text" class="form-control" [(ngModel)]="name" name="name">
        </div>
        <div class="form-group">
            <label for="email">Email</label>
            <input type="email" class="form-control" [(ngModel)]="email" name="email">
        </div>
        <div class="form-group">
            <label for="password">Password</label>
            <input type="password" class="form-control" [(ngModel)]="password" name="password">
        </div>
        <div class="text-center">
            <input type="submit" class="btn btn-primary" value="Submit">
        </div>
    </form>
</div>

// react_src/src/pages/register/register.js
import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { validateRegister, validateEmail } from '../../services/validationService';
import { registerUser } from '../../services/authService';
import './register.css';

const Register = () => {
  const [user, setUser] = useState({ name: '', email: '', password: '' });
  const navigate = useNavigate();

  const onRegisterSubmit = async (e) => {
    e.preventDefault();

    // Validate form fields
    if (!validateRegister(user)) {
      alert('Please fill in all fields.');
      return;
    }

    // Validate email format
    if (!validateEmail(user.email)) {
      alert('Please use a valid email address.');
      return;
    }

    // Proceed with registration
    const response = await registerUser(user);
    if (response.success) {
      alert('You are now registered and can log in.');
      navigate('/login');
    } else {
      alert('Something went wrong. Please try again.');
      navigate('/register');
    }
  };

  return (
    <div className="container">
      <h2 className="page-header">Register</h2>
      <form onSubmit={onRegisterSubmit}>
        <div className="form-group">
          <label htmlFor="name">Name</label>
          <input
            type="text"
            className="form-control"
            value={user.name}
            onChange={(e) => setUser({ ...user, name: e.target.value })}
            required
          />
        </div>
        <div className="form-group">
          <label htmlFor="email">Email</label>
          <input
            type="email"
            className="form-control"
            value={user.email}
            onChange={(e) => setUser({ ...user, email: e.target.value })}
            required
          />
        </div>
        <div className="form-group">
          <label htmlFor="password">Password</label>
          <input
            type="password"
            className="form-control"
            value={user.password}
            onChange={(e) => setUser({ ...user, password: e.target.value })}
            required
          />
        </div>
        <div className="text-center">
          <input type="submit" className="btn btn-custom" value="Register" />
        </div>
      </form>
    </div>
  );
};

export default Register;
