// angular_src/src/app/components/navbar/navbar.component.ts
import { Component } from '@angular/core';
import { Router, RouterLink } from '@angular/router';
import { FormsModule } from '@angular/forms';
import { AuthService } from '../../services/auth.service';

@Component({
  selector: 'app-navbar',
  standalone: true,
  imports: [RouterLink],
  templateUrl: './navbar.component.html',
  styleUrl: './navbar.component.css'
})
export class NavbarComponent {

  constructor(
    private authService: AuthService,
    private router: Router
  ) {}

  onLogoutClick() {
    // Logout the user
    this.authService.logout();
    // Show a success message
    alert('You are now logged out.');
    // Redirect to the login page
    this.router.navigate(['/login']);
    return false;
  }
}

<nav class="navbar navbar-expand-lg bg-dark" data-bs-theme="dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="/">Grow & Give</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
  
      <div class="collapse navbar-collapse" id="navbarNav" pull-right>
        <ul class="navbar-nav ms-auto text-center">
          <li class="nav-item" routerLinkActive="active" routerLinkActiveOptions="{exact: true}">
            <a class="nav-link" routerLink="/">Home</a>
          </li>
          <li class="nav-item" routerLinkActive="active" routerLinkActiveOptions="{exact: true}">
            <a class="nav-link" routerLink="/dashboard">About us</a>
          </li>
          <li class="nav-item" routerLinkActive="active" routerLinkActiveOptions="{exact: true}">
            <a class="nav-link" routerLink="/dashboard">Contact</a>
          </li>
          <li class="nav-item" routerLinkActive="active" routerLinkActiveOptions="{exact: true}">
            <a class="nav-link" routerLink="/login">Login</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" (click)="onLogoutClick()" href="#">Logout</a>
          </li>
        </ul>
      </div>

    </div>
</nav>

// react_src/src/components/nav/navbar.js
import React from 'react';
import { Link, useNavigate } from 'react-router-dom';
import './navbar.css';
import { logout } from '../../services/authService';  // Import logout function from authService

const Navbar = ({ isLoggedIn, setIsLoggedIn }) => {
  const navigate = useNavigate();

  const handleLogout = () => {
    logout(); // Call the authService's logout function
    setIsLoggedIn(false); // Update the logged-in state
    alert('You are now logged out.');
    navigate('/login');
  };

  return (
    <nav className="navbar navbar-expand-lg bg-dark" data-bs-theme="dark">
      <div className="container-fluid">
        <a className="navbar-brand" href="/">React Auth App</a>
        <button className="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span className="navbar-toggler-icon"></span>
        </button>

        <div className="collapse navbar-collapse" id="navbarNav">
          <ul className="navbar-nav ms-auto text-center">
            {!isLoggedIn ? (
              <>
                <li className="nav-item">
                  <Link className="nav-link" to="/login">Login</Link>
                </li>
                <li className="nav-item">
                  <Link className="nav-link" to="/register">Register</Link>
                </li>
              </>
            ) : (
              <>
                <li className="nav-item">
                  <Link className="nav-link" to="/profile">Profile</Link>
                </li>
                <li className="nav-item">
                  <button className="nav-link btn btn-link" onClick={handleLogout}>Logout</button>
                </li>
              </>
            )}
          </ul>
        </div>
      </div>
    </nav>
  );
};

export default Navbar;
