// react_src/src/pages/login/login.js
import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { authenticateUser, storeUserData } from '../../services/authService.js';
import './login.css';

const Login = ({ setIsLoggedIn }) => {
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const navigate = useNavigate();

  const onLoginSubmit = async (e) => {
    e.preventDefault();

    const user = {
      email,
      password,
    };

    const response = await authenticateUser(user);
    if (response.success) {
      storeUserData(response.token, response.user);
      setIsLoggedIn(true);
      alert('You are now logged in.');
      navigate('/profile');
    } else {
      alert('Login failed. Please check your credentials.');
    }
  };
 
  return (
    <div className="container" id="login-container">
      <h2 className="page-header">Login</h2>
      <form onSubmit={onLoginSubmit}>
        <div className="form-group" id="login-form-group">
          <label htmlFor="email">Email</label>
          <input
            type="email"
            className="form-control"
            value={email}
            onChange={(e) => setEmail(e.target.value)}
            name="email"
            required
          />
        </div>
        <div className="form-group" id="login-form-group">
          <label htmlFor="password">Password</label>
          <input
            type="password"
            className="form-control"
            value={password}
            onChange={(e) => setPassword(e.target.value)}
            name="password"
            required
          />
        </div>
        <div className="text-center">
          <input type="submit" className="btn btn-custom" value="Submit" id="login-btn"/>
          <a className="btn btn-custom" href="/register" id="login-btn">Register</a>
        </div>
      </form>
    </div>
  );
};

export default Login;

// angular_src/src/app/components/login/login.component.ts
import { Component } from '@angular/core';
import { Router } from '@angular/router';
import { FormsModule } from '@angular/forms';
import { AuthService } from '../../services/auth.service';

@Component({
  selector: 'app-login',
  standalone: true,
  templateUrl: './login.component.html',
  imports: [FormsModule],
  styleUrls: ['./login.component.css']
})
export class LoginComponent {
  email: string = '';
  password: string = '';

  constructor(
    private authService: AuthService,
    private router: Router
  ) {}

  onLoginSubmit() {
    const user = {
      email: this.email,
      password: this.password
    };

    this.authService.authenticateUser(user).subscribe(data => {
      if (data.success) {
        this.authService.storeUserData(data.token, data.user);
        alert('You are now logged in.');
        this.router.navigate(['/profile']);
      } else {
        alert('Login failed. Please try again.');
        this.router.navigate(['/login']);
      }
    });
  }
}

<div class="container">
    <h2>Login</h2>
  
    <form formGroup="loginForm" (ngSubmit)="onSubmit()">
      <!-- Email Input -->
      <div class="form-group mb-3">
        <label for="email">Email</label>
        <input type="email" id="email" formControlName="email" class="form-control" ngClass="{'is-invalid': submitted && f.email.errors}">
        <div *ngIf="submitted && f.email.errors" class="invalid-feedback">
          <div *ngIf="f.email.errors?.required">Email is required</div>
          <div *ngIf="f.email.errors?.email">Invalid email format</div>
        </div>
      </div>
  
      <!-- Password Input -->
      <div class="form-group mb-3">
        <label for="password">Password</label>
        <input type="password" id="password" formControlName="password" class="form-control" ngClass="{'is-invalid': submitted && f.password.errors}">
        <div *ngIf="submitted && f.password.errors" class="invalid-feedback">
          <div *ngIf="f.password.errors?.required">Password is required</div>
          <div *ngIf="f.password.errors?.minlength">Password must be at least 6 characters</div>
        </div>
      </div>
  
      <!-- Error Message -->
      <div *ngIf="errorMessage" class="alert alert-danger">
        {{ errorMessage }}
      </div>
  
      <!-- Submit Button -->
      <button type="submit" class="btn btn-primary">Login</button>
    </form>
  </div>
